### ISSUE TITLE
[warning] failed package validation and/or copy for commit 0d82533354fff38c1084005c20b43abac64d1a64

### ISSUE THREAD

**Issue by conda-forge-daemon** [conda-forge/plumbum-feedstock#12]
Hi @conda-forge/plumbum! This is the friendly automated conda-forge-webservice!

It appears that one or more of your feedstock's outputs is either invalid or
did not copy from the staging channel (cf-staging) to the production channel (conda-forge). :(

This failure can happen for a lot of reasons, including an outdated feedstock
token, a feedstock output that is not allowed for that feedstock, or a feedstock output
with files that are not allowed for that output. Below we have put some information
about the failure to help you debug it.

**Rerendering the feedstock will usually fix these problems.**

If you have any issues or questions, you can find us on gitter in the
community [chat room](https://gitter.im/conda-forge/conda-forge.github.io) or you can bump us right here.

error messages:
 - invalid md5 sum for artifact https://conda.anaconda.org/cf-staging/noarch/plumbum-1.7.0-pyhd8ed1ab_0.tar.bz2

**Comment by henryiii** [comment]
Rerendered, we'll see if it happens again...
